### ISSUE TITLE
Add department drop down

### ISSUE THREAD

**Issue by rstein66** [rrshaban/swatcore-dev#8]
Medium priority (Rachel)

Have user assign a new review to a department by selecting it from a dropdown

**Comment by rstein66** [comment]
Are we supporting Bryn Mawr, Haverford, and Penn classes? If so, how do we want to assign them?

**Comment by rrshaban** [comment]
I say no, at least for the forseeable future. This is the Swarthmore Course Review, and the vision is a local utility.

**Comment by rrshaban** [comment]
done
